name: android
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            architecture: i686
          - runner: ubuntu-24.04
            architecture: x86_64
          - runner: ubuntu-24.04-arm
            architecture: arm
          - runner: ubuntu-24.04-arm
            architecture: aarch64
    runs-on: ${{ matrix.runner }}
    container:
      image: termux/termux-docker:${{ matrix.architecture }}
      volumes: 
        - /tmp/node20:/__e/node20
    env:
      ANDROID_ROOT: /system
      ANDROID_DATA: /data
      PREFIX: /data/data/com.termux/files/usr
      HOME: /data/data/com.termux/files/home
      PATH: /data/data/com.termux/files/usr/bin
      TMPDIR: /data/data/com.termux/files/usr/tmp
      LANG: en_US.UTF-8
      TZ: UTC
    steps:
      - name: Set Termux Package Mirror
        run: ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
      
      - name: Cache Termux Packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PREFIX }}/var/lib/apt/lists
            ${{ env.PREFIX }}/var/cache/apt
          key: termux-packages-${{ matrix.architecture }}-${{ github.run_id }}
          restore-keys: termux-packages-${{ matrix.architecture }}-

      - name: Upgrade Packages
        run: /entrypoint.sh bash -c "yes | pkg upgrade -y"
      
      - name: Fix Executable Permissions
        run: chmod -R o+x ${PREFIX}/bin

      - name: Cache Node.js Modules
        uses: actions/cache@v4
        with:
          path: ${{ env.PREFIX }}/var/lib/node_modules
          key: termux-node-modules-${{ matrix.architecture }}-${{ github.run_id }}
          restore-keys: termux-node-modules-${{ matrix.architecture }}-

      - name: Install Node.js
        run: |
          /entrypoint.sh pkg install -y nodejs-lts
          ln -sf ${PREFIX}/bin /__e/node20/bin

      - uses: actions/checkout@v4.2.2

      - name: Fix Repository Permissions
        run: chown -R 1000:1000 .

      - name: Cache Built Artifacts
        uses: actions/cache@v4
        with:
          path: platform/android/android/lib
          key: android-lib-${{ matrix.architecture }}-${{ github.run_id }}
          restore-keys: android-lib-${{ matrix.architecture }}-

      - name: Build
        run: /entrypoint.sh .github/build-android.sh

      - uses: actions/upload-artifact@v4.6.0
        with:
          name: main-${{ matrix.architecture }}
          path: build/us_pc/libmain.so

      - uses: actions/upload-artifact@v4.6.0
        with:
          name: libc++-${{ matrix.architecture }}
          path: ${{ env.PREFIX }}/lib/libc++_shared.so

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y zipalign apksigner

      - uses: actions/checkout@v4.2.2
      
      - name: Cache Built Artifacts
        uses: actions/cache@v4
        with:
          path: platform/android/android/lib
          key: android-lib-merge-${{ github.run_id }}
          restore-keys: android-lib-

      - name: Fetch All Architecture Libraries
        uses: actions/download-artifact@v4
        with:
          pattern: "main-*"
          merge-multiple: true
          path: platform/android/android/lib/

      - name: Fetch All Architecture C++ Libraries
        uses: actions/download-artifact@v4
        with:
          pattern: "libc++-*"
          merge-multiple: true
          path: platform/android/android/lib/

      - name: Generate Merged APK
        run: |
          mkdir platform/android/android/assets/
          cp -r {mods,lang,palettes,dynos} platform/android/android/assets/
          pushd platform/android/android/
          zip -0 -r ../../../sm64coopdx_unaligned.zip ./*
          popd
          zipalign -f -p 4 sm64coopdx_unaligned.zip sm64coopdx.apk
          apksigner sign --cert platform/android/certificate.pem \
                          --key platform/android/key.pk8 \
                          sm64coopdx.apk

      - uses: actions/upload-artifact@v4.6.0
        with:
          name: sm64coopdx apk
          path: sm64coopdx.apk
